version: "3.8"
services:
  frontend:
    build: .
    container_name: bengkala-frontend
    restart: unless-stopped
    ports:
      - "3000:3000" 
    networks:
      - bengkala-network

networks:
  bengkala-network:
    external: true
